/**
 * dev-local.mjs — run the seller locally without a Cloudflare account.
 *
 * `npx wrangler dev` needs a Cloudflare login for this project. The Workers AI
 * binding always runs remotely, even in local development, so wrangler opens a
 * browser to authorize, and without an account it fails with:
 *
 *   ✘ [ERROR] Failed to start the remote proxy session …
 *     Timed out waiting for authorization code, please try again.
 *
 * A first-time tester hit exactly that on 2026-09-14, following the README.
 *
 * This script reads wrangler.jsonc, drops the `ai` binding, writes the result
 * to wrangler.local.jsonc (gitignored, regenerated on every run, so it cannot
 * drift from the real config) and starts `wrangler dev` with it. Everything
 * else is local: the DeviceTwin and RateLimiter Durable Objects, KV, the payment
 * gate. Payments still settle on Base Sepolia through the public facilitator.
 * Only /api/inference is missing, and it answers 503 inference_unavailable.
 *
 * Run: npm run dev:local            (extra args pass through, e.g. -- --port 8799)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { spawn } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "wrangler.jsonc");
const TARGET = join(ROOT, "wrangler.local.jsonc");

/** Remove // and /* *\/ comments outside strings, and trailing commas. */
function parseJsonc(text) {
  let out = "";
  let inString = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    const next = text[i + 1];
    if (inString) {
      out += ch;
      if (ch === "\\") {
        out += next;
        i++;
      } else if (ch === '"') {
        inString = false;
      }
      continue;
    }
    if (ch === '"') {
      inString = true;
      out += ch;
    } else if (ch === "/" && next === "/") {
      while (i < text.length && text[i] !== "\n") i++;
      out += "\n";
    } else if (ch === "/" && next === "*") {
      i += 2;
      while (i < text.length && !(text[i] === "*" && text[i + 1] === "/")) i++;
      i++;
    } else {
      out += ch;
    }
  }
  return JSON.parse(out.replace(/,(\s*[}\]])/g, "$1"));
}

const config = parseJsonc(readFileSync(SOURCE, "utf8"));
const hadAi = Boolean(config.ai);
delete config.ai;

writeFileSync(
  TARGET,
  "// GENERATED by scripts/dev-local.mjs from wrangler.jsonc — do not edit, not committed.\n" +
    "// Identical to wrangler.jsonc except the Workers AI binding, which needs a Cloudflare login.\n" +
    JSON.stringify(config, null, 2) +
    "\n"
);

console.log(
  hadAi
    ? "[dev-local] Starting the seller WITHOUT Workers AI (no Cloudflare account needed).\n" +
        "[dev-local] /api/readings works and settles on testnet as normal.\n" +
        "[dev-local] /api/inference answers 503 inference_unavailable. For it, run `npx wrangler login` once, then `npx wrangler dev`.\n"
    : "[dev-local] wrangler.jsonc has no AI binding; starting as-is.\n"
);

const child = spawn("npx", ["wrangler", "dev", "-c", "wrangler.local.jsonc", ...process.argv.slice(2)], {
  cwd: ROOT,
  stdio: "inherit",
  shell: process.platform === "win32",
});
child.on("exit", (code) => process.exit(code ?? 0));
for (const sig of ["SIGINT", "SIGTERM"]) process.on(sig, () => child.kill(sig));
