/**
 * types.ts — Single source of truth for shared interfaces and bindings.
 * All Workers and Durable Object code imports from here.
 */

// ---------------------------------------------------------------------------
// Sensor data
// ---------------------------------------------------------------------------

export interface SensorReading {
  /** Unique monotonic sequence number; starts at 1, never repeats. */
  seq: number;
  /** Device identifier from env.DEVICE_ID */
  device_id: string;
  /** Simulated temperature in Celsius, range 18–27 °C */
  temperature_c: number;
  /** Simulated relative humidity, range 40–80 % */
  humidity_pct: number;
  /** ISO-8601 UTC timestamp of the reading */
  ts: string;
  /** Always "TESTNET — no real value" to prevent confusion */
  note: string;
}

// ---------------------------------------------------------------------------
// Worker environment bindings (generated by `wrangler types` then extended here)
// ---------------------------------------------------------------------------

export interface Env {
  // Durable Object namespace — one global device twin
  DEVICE_TWIN: DurableObjectNamespace;

  // KV namespace — idempotency keys + receipt log + rate-limit windows
  IOT_KV: KVNamespace;

  // Seller address that receives x402 payments
  PAY_TO: string;

  // x402 facilitator endpoint
  FACILITATOR_URL: string;

  // Human-readable device identifier used as the DO name
  DEVICE_ID: string;

  // Tick interval in milliseconds; parsed defensively, defaults to 60000
  TICK_INTERVAL_MS: string;

  // Price per reading, e.g. "$0.001"
  PRICE_PER_READING: string;

  // Price per inference run, e.g. "$0.002" — higher than a reading, because
  // compute costs more to produce than a stored measurement
  PRICE_PER_INFERENCE: string;

  // Rate-limit quota per window, e.g. "10"
  RATE_LIMIT_QUOTA: string;

  // Rate-limit window in seconds, e.g. "60"
  RATE_LIMIT_WINDOW_S: string;

  // Expected settlement asset (Base Sepolia USDC contract address)
  USDC_ASSET: string;

  // "true" to reject requests that present no mandate at all (403).
  // Default false: a mandate is verified when presented, but not demanded,
  // so the Week 2 single-purchase script keeps working.
  REQUIRE_MANDATE: string;

  // Comma-separated addresses we control. Any payer NOT on this list counts as
  // external adoption. Keeping it in config rather than in a report is what
  // stops a wallet we funded ourselves being counted as a stranger.
  OWN_WALLETS: string;

  // Secret guarding the subscriber CSV export. Set with:
  //   npx wrangler secret put EXPORT_TOKEN
  // If unset, the export endpoint returns 503 and exports nothing.
  EXPORT_TOKEN?: string;

  // Workers AI binding, used by the pay-per-inference resource
  AI: { run: (model: string, input: Record<string, unknown>) => Promise<any> };
}

// ---------------------------------------------------------------------------
// DeviceTwin internal storage shape
// ---------------------------------------------------------------------------

export interface DeviceTwinState {
  latest: SensorReading;
  seq: number;
  history: SensorReading[];
}
